### ISSUE TITLE
CGRAN Site is down

### ISSUE THREAD

**Issue by ruffyontheweb** [gnuradio/cgran#34]
Hello Prof Lichtman, sorry to bother you, but the CGRAN site seems to be down. https://www.cgran.org is showing

`502 Bad Gateway
nginx`

**Comment by 777arc** [comment]
Thanks for the heads up, we'll look into it, it's hosted alongside other gnuradio stuff like gnuradio.org so not sure what's going on

**Comment by ruffyontheweb** [comment]
> Thanks for the heads up, we'll look into it, it's hosted alongside other gnuradio stuff like gnuradio.org so not sure what's going on

Yup! If you don't mind me asking, what is the best place for community? Is it the matrix server #gnuradio:gnuradio.org listed in [the newbie guide](https://wiki.gnuradio.org/index.php/Newbie_Guide_to_GNU_Radio)?

**Comment by 777arc** [comment]
Yea definitely the gnuradio matrix server, as far as which channel, I would start with general chat for misc gnuradio or OOT questions
