### ISSUE TITLE
gr-iqbal and gr-fosphor are hardcoded

### ISSUE THREAD

**Issue by smunaut** [gnuradio/cgran#7]
Instead of hard-coding the actual data, it could at least just hard code the URL of the mirrors on github and fetch the data dynamically from there instead of the primary repo.

**Comment by 777arc** [comment]
Ah yes that would make sense, thanks!

**Comment by dkozel** [comment]
Currently CGRAN only tries loading YAML files that are hosted on GitHub. Loading from the mirror should be a quick solution that's less bad than the current. Maybe recipes should support an optional URL for the manifest?

https://github.com/gnuradio/cgran/blob/895d4e85892331018ee269138c882bbd5ecbf989/ootlist/management/commands/refresh.py#L101

**Comment by 777arc** [comment]
Yeah if the recipe had a url pointing directly to the MANIFEST file, then I could deal with these "custom" urls

**Comment by 777arc** [comment]
For the sake of getting something simple and clean working, CGRAN now looks for a "mirror" tag within recipes, if it's there then it uses it in place of the "source", simple as that.  So I added the mirror tag to gr-iqimbal and gr-fosphor, and now those 2 repos no longer need to be hard-coded within CGRAN code and now are updating live https://www.cgran.org/ =)
